package com.example.xts.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.day02_text.model.bean.RecentBean;

import com.example.xts.greendaodemo.db.RecentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentBeanDaoConfig;

    private final RecentBeanDao recentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentBeanDaoConfig = daoConfigMap.get(RecentBeanDao.class).clone();
        recentBeanDaoConfig.initIdentityScope(type);

        recentBeanDao = new RecentBeanDao(recentBeanDaoConfig, this);

        registerDao(RecentBean.class, recentBeanDao);
    }
    
    public void clear() {
        recentBeanDaoConfig.clearIdentityScope();
    }

    public RecentBeanDao getRecentBeanDao() {
        return recentBeanDao;
    }

}
